image: node:5

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

services:
  - mongo

variables:
  MONGO_URI: 'mongodb://mongo/showsnearme-api-test'
  NODE_ENV: 'test'

all_tests:
  script:
    - npm install
    - npm test
