version: '2'

services:
  db:
    image: mongo

  api:
    build: .
    command: npm start
    volumes:
      - .:/opt/api
    ports:
      - "3000:3000"
    links:
      - db
      - parser

  parser:
    image: registry.gitlab.com/showsnearme/parser:latest
    command: npm start
    expose:
      - "3000"
