version: '2'

services:
  db:
    image: mongo

  api:
    build: .
    command: npm start
    volumes:
      - .:/opt/api
    ports:
      - "3000:3000"
    depends_on:
      - db

  parser:
    image: registry.gitlab.com/showsnearme/parser
    command: npm start
    ports:
      - "3001:3000"
